---
- name: NFS 클라이언트 설정
  gather_facts: yes
  become: yes

  hosts: managed

  vars_files:
    - vars/vars_nfs.yml

  tasks:
    - name: NFS 패키지 설치
      apt:
        name: nfs-common
        state: present
    
    - name: 마운트 폴더 생성
      file:
        path: "{{ mount_point }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
  
    - name: "/etc/fstab에 NFS 마운트 정보 추가 및 마운트 실행"
      mount:
        src: "{{ nfs_server }}:{{ nfs_export_path }}"
        path: "{{ mount_point }}"
        fstype: nfs
        opts: rw,sync
        state: mounted
      become: true
