- hosts: servers
  become: yes
  tasks:
    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
    
    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Configure Prometheus
      template:
        src: prometheus.yml.j2
        dest: /opt/prometheus-2.37.0.linux-amd64/prometheus.yml

    - name: Create Prometheus systemd service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service

    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started
