---
- name: MariaDB 설치 플레이북
  gather_facts: yes
  become: yes
  hosts: servers

  vars_files:
    - vars/vars_mariadb.yml

  tasks:
    - name: 기존 MariaDB 제거
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: absent
        purge: yes
        autoremove: yes

    - name: 남은 MariaDB 설정 파일 제거
      file:
        path: /etc/mysql
        state: absent
      ignore_errors: yes