---
- hosts: all

  vars:
    supported_distros:
    - RedHat
    - CentOS

  tasks:
  - name: 운영체제 검사하기
    ansible.builtin.debug:
      mag: "This {{ ansible_fatcs['distribution'] }} need to use dnf"
    when: ansible_facts['distribution'] in supported_distros