---
- name: Install Java and set JAVA_HOME environment variable
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: /etc/environment
        line: JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
        create: yes

    - name: Refresh environment
      command: bash -c "source /etc/environment && echo $JAVA_HOME"
      args:
        executable: /bin/bash
      register: echo_java_home

    - debug:
        msg: "{{ echo_java_home.stdout }}"
