- name: Prepare Kubernetes Nodes
  hosts: all
  become: yes
  tasks:
    - name: Disable swap
      shell: swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Load br_netfilter module
      shell: |
        echo 'br_netfilter' > /etc/modules-load.d/k8s.conf
        modprobe br_netfilter

    - name: Set sysctl params
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
      notify: Reload sysctl

    - name: Add hosts entries
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "192.168.32.10 k8s-master"
        - "192.168.32.11 k8s-node01"
        - "192.168.32.12 k8s-node02"

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

  handlers:
    - name: Reload sysctl
      command: sysctl --system