Vagrant_API_Version="2"

Vagrant.configure(Vagrant_API_Version) do |config|
  # Ansible 제어 노드 설정
  config.vm.define "controll-node" do |master|
    master.vm.box = "generic/ubuntu2004"
    master.vm.provider :virtualbox do |vb|
      vb.name = "controll-node"
      vb.cpus = 2
      vb.memory = 2048
    end
    master.vm.hostname = "controll-node"
    master.vm.synced_folder ".", "/vagrant"
    master.vm.network "private_network", ip: "192.168.32.14"

    master.vm.network "forwarded_port", guest: 80, host: 10080, auto_correct: true
    
    master.vm.provision "shell", path: "sshd_config.sh"
  end

  # Ansible 관리 노드 1 설정
  config.vm.define "manage-node-1" do |node1|
    node1.vm.box = "generic/ubuntu2004"
    node1.vm.provider :virtualbox do |vb|
      vb.name = "manage-node-1"
      vb.cpus = 2
      vb.memory = 2048
    end
    node1.vm.hostname = "manage-node-1"
    node1.vm.synced_folder ".", "/vagrant"
    node1.vm.network "private_network", ip: "192.168.32.15"

    node1.vm.network "forwarded_port", guest: 80, host: 20080, auto_correct: true
    
    node1.vm.provision "shell", path: "sshd_config.sh"
  end

   # Ansible 관리 노드 2 설정
    config.vm.define "manage-node-2" do |node2|
      node2.vm.box = "generic/ubuntu2004"
      node2.vm.provider :virtualbox do |vb|
        vb.name = "manage-node-2"
        vb.cpus = 2
        vb.memory = 2048
      end
      node2.vm.hostname = "manage-node-2"
      node2.vm.synced_folder ".", "/vagrant"
      node2.vm.network "private_network", ip: "192.168.32.16"
  
      node2.vm.network "forwarded_port", guest: 80, host: 30080, auto_correct: true
      
      node2.vm.provision "shell", path: "sshd_config.sh"
    end
end
